name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo  
        uses: actions/checkout@v3

+     # 1) Install PHP + intl on the runner
-     - name: Set up PHP
-       uses: webfactory/ssh-agent@v0.5.3
-       with:
-         php-version: '8.4'  
-         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}     # ili verzija koju koristiš
-         extensions: intl, mbstring, pdo_mysql, zip
-         ini-values: post_max_size=256M, max_execution_time=180
-         tools: composer:v2
+     - name: Set up PHP
+       uses: shivammathur/setup-php@v2
+       with:
+         php-version: '8.3'            # or whatever your lock file needs
+         extensions: intl, mbstring, pdo_mysql, zip
+         ini-values: post_max_size=256M, max_execution_time=180

      # 2) Install Node.js dependencies & build assets
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run build

      # 3) Install PHP deps
      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # 4) Run migrations & optimize
      - run: php artisan migrate --force
      - run: php artisan optimize

      # 5) Deploy to your server
      - name: Deploy to Server
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /var/www/html/diagnose
            git fetch origin
            git reset --hard origin/master
            composer install --no-dev --optimize-autoloader
            npm ci
            npm run build
            php artisan migrate --force
            sudo systemctl restart apache2
          EOF
