name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 1) Postavi PHP i neophodne ekstenzije, uključujući intl
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'       # ili verzija koju koristiš
          extensions: intl, mbstring, pdo_mysql, zip
          ini-values: post_max_size=256M, max_execution_time=180
          tools: composer:v2

      # 2) Instaliraj npm zavisnosti i izgradi asset-e
      - name: Install Node.js dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run build

      # 3) Instaliraj PHP zavisnosti
      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # 4) Migrate, test, deploy…
      - run: php artisan migrate --force
      - run: php artisan optimize

      # 5) (po potrebi) Deploy komanda
      - name: Deploy to server
        run: ssh user@host 'cd /path/to/app && git pull && php artisan migrate --force && php artisan optimize'
